name: Debug

on:
  schedule:
    - cron: "15 1,13 * * *"
  workflow_dispatch:

jobs:
  run_arxiv_sanity_bot:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v2
    - name: Setup upterm session
      env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
      uses: lhotari/action-upterm@v1